build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.3
      cache:
        disabled: false
        directories:
          - ~/.composer/cache
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run
          - command: ./bin/phpunit -c phpunit.xml.dist
            coverage:
              file: build/coverage.xml
              format: clover
  dependencies:
    override:
      - composer self-update --no-interaction --no-progress
      - composer install --no-interaction

filter:
  excluded_paths:
    - docs
    - vendor
    - tests
