version: '3.2'
services:
  web:
    image: rrcfesc/lamp:7.3
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/public
      - ./.composer:/home/rioxygen/.composer
    container_name: "rioxygen-sat-web"